In [1]:
import lux
from vega_datasets import data

In [2]:
df = data.cars()

In [3]:
_ = df.Origin
_ = df.describe()
df.history

[
<Event (id: 140510400007808) @[3]: col_ref, cols=['Origin']> with weight 0.475,
<Event (id: 140509202021488) @[3]: describe, cols=['Miles_per_Gallon', 'Cylinders', 'Displacement', 'Horsepower', 'Weight_in_lbs', 'Acceleration']> with weight 1.0
]

In [4]:
df._history.to_JSON()

AttributeError: 'History' object has no attribute 'to_JSON'

In [6]:
df

/Users/wepperso/opt/anaconda3/envs/lux_workspace/lib/python3.9/site-packages/IPython/core/formatters.py:918: UserWarning:
Unexpected error in rendering Lux widget and recommendations. Falling back to Pandas display.
Please report the following issue on Github: https://github.com/lux-org/lux/issues

/Users/wepperso/opt/anaconda3/envs/lux_workspace/lib/python3.9/site-packages/lux/core/frame.py:712: UserWarning:Traceback (most recent call last):
  File "/Users/wepperso/opt/anaconda3/envs/lux_workspace/lib/python3.9/site-packages/lux/core/frame.py", line 674, in _ipython_display_
    self.maintain_recs()
  File "/Users/wepperso/opt/anaconda3/envs/lux_workspace/lib/python3.9/site-packages/lux/core/frame.py", line 528, in maintain_recs
    self._widget = rec_df.render_widget()
  File "/Users/wepperso/opt/anaconda3/envs/lux_workspace/lib/python3.9/site-packages/lux/core/frame.py", line 762, in render_widget
    return luxwidget.LuxWidget( # widget
  File "/Users/wepperso/Documents/Research/Projects/Notebook_Vis_Rec_Projects/lux-widget/luxwidget/widget.py", line 37, in __init__
    self.history_list = history_list
  File "/Users/wepperso/opt/anaconda3/envs/lux_workspace/lib/python3.9/site-packages/traitlets/traitlets.py", line 604, in __set__
    self.set(obj, value)
  File "/Users/wepperso/opt/anaconda3/envs/lux_workspace/lib/python3.9/site-packages/traitlets/traitlets.py", line 578, in set
    new_value = self._validate(obj, value)
  File "/Users/wepperso/opt/anaconda3/envs/lux_workspace/lib/python3.9/site-packages/traitlets/traitlets.py", line 610, in _validate
    value = self.validate(obj, value)
  File "/Users/wepperso/opt/anaconda3/envs/lux_workspace/lib/python3.9/site-packages/traitlets/traitlets.py", line 2496, in validate
    value = super(Container, self).validate(obj, value)
  File "/Users/wepperso/opt/anaconda3/envs/lux_workspace/lib/python3.9/site-packages/traitlets/traitlets.py", line 1845, in validate
    self.error(obj, value)
  File "/Users/wepperso/opt/anaconda3/envs/lux_workspace/lib/python3.9/site-packages/traitlets/traitlets.py", line 690, in error
    raise TraitError(e)
traitlets.traitlets.TraitError: The 'history_list' trait of a LuxWidget instance expected a list, not the NoneType None.

,Name,Miles_per_Gallon,Cylinders,Displacement,Horsepower,Weight_in_lbs,Acceleration,Year,Origin
0,chevrolet chevelle malibu,18.0,8,307.0,130.0,3504,12.0,1970-01-01,USA
1,buick skylark 320,15.0,8,350.0,165.0,3693,11.5,1970-01-01,USA
2,plymouth satellite,18.0,8,318.0,150.0,3436,11.0,1970-01-01,USA
3,amc rebel sst,16.0,8,304.0,150.0,3433,12.0,1970-01-01,USA
4,ford torino,17.0,8,302.0,140.0,3449,10.5,1970-01-01,USA
...,...,...,...,...,...,...,...,...,...
401,ford mustang gl,27.0,4,140.0,86.0,2790,15.6,1982-01-01,USA
402,vw pickup,44.0,4,97.0,52.0,2130,24.6,1982-01-01,Europe
403,dodge rampage,32.0,4,135.0,84.0,2295,11.6,1982-01-01,USA
404,ford ranger,28.0,4,120.0,79.0,2625,18.6,1982-01-01,USA
405,chevy s-10,31.0,4,119.0,82.0,2720,19.4,1982-01-01,USA